#!/usr/bin/env php
<?php
// console

require_once 'vendor/autoload.php';
require_once 'src/GetPlanningCommand.php';
require_once 'src/PlanningService.php';

use src\GetPlanningCommand;
use src\PlanningService;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GetPlanningCommand);
$application->run();